### ISSUE TITLE
twilio dont work properly

### ISSUE THREAD

**Issue by jclm-rt** [automateyournetwork/Modern_Show_Version#1]
Hello @johncapobianco  @automateyournetwork  
Please your help with the part of your code where the mp3 will be sent to twilio to make the call. What url address do you put in "call = client.calls.create **(url = '{{MP3 File location}}'),** ..." I took your code as an example but instead of google tts I use aws polly tts . Everything works fine until the part of the code where the connection with the twilio api starts, the call is not generated. I put in that "url" first a github address and then a soundcloud address with the loaded mp3 file generated by polly aws, the code accepts this data however the call is not generated. Additionally, let you know that I tried with a call example provided by twilio 
[https://www.twilio.com/docs/voice/tutorials/how-to-make-outbound-phone-calls-python#](url) however it works very sporadically, It seems that the twilio api does not work well or maybe I am failing something (most likely :-)). Please your help, I thank you in advance.

![example_from_twilio](https://user-images.githubusercontent.com/55666859/133927367-104e087a-6601-4cce-b9f9-9f6cf8c20392.png)

label:bug

**Comment by automateyournetwork** [comment]
Hi!

Thank you for your interest and it sounds like you are very close

Here is my working code I used for a demo that might help you ? Let me know

## Twilio
for interface,value in self.parsed_show_ip_int_brief['interface'].items():
if value['status'] != "up":
account_sid = "{{ YOUR SID }}"
auth_token = "{{ YOUR TOKEN }}"
client = Client(account_sid, auth_token)
call = client.calls.create(
url='
https://www.automateyournetwork.ca/wp-content/uploads/2021/05/DevNet_Sandbox_CSR1000v_Heavy_Networking-2.mp3
',
to='+{{ TO NUMBER }}',
from_='{{ FROM NUMBER }}'
)

**Comment by jclm-rt** [comment]
Thank you very much for the help, I tried your mp3 but in the same way I have an unstable result since sometimes the call occurs and other times it does not. Unfortunately it seems that twilio does not work well with my country Bolivia, at least I was able to successfully integrate pyats, slack and aws polly and partially with twilio. Your videos and tutorials are great, until next time.
